### ISSUE TITLE
UnhandledPromiseRejectionWarning: HTTPError: Response code 406

### ISSUE THREAD

**Issue by rustypasini** [DustinBryant/MMM-Ring#13]
Good afternoon,

First, thanks for your development work on this plug-in.  I know you are looking for someone to take over maintaining it, but I hope you might be able to assist anyway.

I just installed MMM-Ring on my new MM device yesterday.  I was able to follow the process to obtain a 2FA code without any issue.  However, once I enable the plug-in in my config, I get the following error in the logs:

`[2020-06-24 16:52:10.907] [ERROR]  (node:23874) UnhandledPromiseRejectionWarning: HTTPError: Response code 406 (Not Acceptable)
    at onResponse (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/got/dist/source/as-promise/index.js:124:28)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

[2020-06-24 16:52:10.909] [ERROR]  (node:23874) UnhandledPromiseRejectionWarning: HTTPError: Response code 406 (Not Acceptable)
    at onResponse (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/got/dist/source/as-promise/index.js:124:28)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

[2020-06-24 16:52:10.910] [ERROR]  (node:23874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2020-06-24 16:52:10.910] [ERROR]  (node:23874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2020-06-24 16:52:10.911] [ERROR]  (node:23874) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-06-24 16:52:10.912] [ERROR]  (node:23874) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I am able to log into ring.com from the same device with no issue.  And, like I said, I'm able to obtain the 2FA code with no issue.

Would you have any suggestions?  Thank you!

**Comment by DustinBryant** [comment]
Just updated the repository to using the latest ring-client-api to 9.3.3 which apparently solves the 406 error.

Please update MMM-Ring to the latest and let me know if this fixes your issues:

```git pull```
```npm install```

**Comment by rustypasini** [comment]
That fixed it.  Thank you very much!
