### ISSUE TITLE
unable to get token to work,

### ISSUE THREAD

**Issue by Jimster1** [DustinBryant/MMM-Ring#18]
I did have this working fine until a few weeks a, but now I get token errors, I've tried to create new tokens, and updated them in the config, but I still get this error:
`[2020-10-24 17:09:25.642] [ERROR]  (node:1627) UnhandledPromiseRejectionWarning: Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:116:15)
    at RingRestClient.<anonymous> (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:120:36)
    at Generator.next (<anonymous>)
    at /home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:119:16)
    at RingRestClient.<anonymous> (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:143:33)
    at Generator.throw (<anonymous>)
    at rejected (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:25:65)
[2020-10-24 17:09:25.644] [ERROR]  (node:1627) UnhandledPromiseRejectionWarning: Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:116:15)
    at RingRestClient.<anonymous> (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:120:36)
    at Generator.next (<anonymous>)
    at /home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:119:16)
    at RingRestClient.<anonymous> (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:143:33)
    at Generator.throw (<anonymous>)
    at rejected (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:25:65)
`

**Comment by jsiidorov** [comment]
I had also this great module working until 12 Nov. I updated token, and it is still giving me the same errror as Jimster1 decribed earlier. Any thoughts / help is appreciated a lot.

**Comment by jsiidorov** [comment]
I figured out what was the issue... Just update ring-client-api, and token is accepted and update without any issues.
