### ISSUE TITLE
MMM-Ring will not come up as URL in create.js fails

### ISSUE THREAD

**Issue by sushimatt** [DustinBryant/MMM-Ring#33]
My log is showing this, I have already cloned it again, updated node and npm to the latest, resinstalled and still hte same
I have also created the token and nothing works. It is an error of MMM-Ring since if I comment it out of config it works.

Any ideas?

App threw an error during load
0|mm       | /home/pi/MagicMirror/modules/MMM-Ring/node_modules/got/dist/source/create.js:94
0|mm       |                 ...url,
0|mm       |                 ^^^
0|mm       | SyntaxError: Unexpected token ...
0|mm       |     at createScript (vm.js:53:10)
0|mm       |     at Object.runInThisContext (vm.js:95:10)
0|mm       |     at Module._compile (module.js:543:28)
0|mm       |     at Object.Module._extensions..js (module.js:580:10)
0|mm       |     at Module.load (module.js:488:32)
0|mm       |     at tryModuleLoad (module.js:447:12)
0|mm       |     at Function.Module._load (module.js:439:3)
0|mm       |     at Module.require (module.js:498:17)
0|mm       |     at require (internal/module.js:20:19)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/got/dist/source/index.js:14:18)
0|mm       | Whoops! There was an uncaught exception...
0|mm       | /home/pi/MagicMirror/modules/MMM-Ring/node_modules/got/dist/source/create.js:94
0|mm       |                 ...url,
0|mm       |                 ^^^
0|mm       | SyntaxError: Unexpected token ...
0|mm       |     at createScript (vm.js:53:10)
0|mm       |     at Object.runInThisContext (vm.js:95:10)
0|mm       |     at Module._compile (module.js:543:28)
0|mm       |     at Object.Module._extensions..js (module.js:580:10)
0|mm       |     at Module.load (module.js:488:32)
0|mm       |     at tryModuleLoad (module.js:447:12)
0|mm       |     at Function.Module._load (module.js:439:3)
0|mm       |     at Module.require (module.js:498:17)
0|mm       |     at require (internal/module.js:20:19)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/got/dist/source/index.js:14:18)

**Comment by DustinBryant** [comment]
@sushimatt really wish I could help you here but I no longer have a Ring device so I can't test changes or troubleshoot issues.  This code repository is deprecated unless someone forks it and hosts it elsewhere.
